import Navigation from "./components/Navigation";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-black text-white">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
