import AuthProvider from "@/provider/AuthProvider";
import CompareMovieProvider from "@/provider/CompareMovieProvider";
import "./globals.css";

export const metadata = {
  metadataBase: new URL("https://lws-assignment-8-evdw.vercel.app/"),
  title: "Discover Your Favorite Movies - MOVIE DB",
  description: "Generated by create next app",
  openGraph: {
    title: "Discover Your Favorite Movies - MOVIE DB",
    description:
      "Welcome to MOVIE DB, the ultimate destination for movie lovers! Explore a vast collection of movies, from the latest blockbusters to timeless classics. Our site offers comprehensive movie details, including synopses, trailers, ratings, and in-depth reviews, ensuring you never miss out on the best cinema experiences.",
    images: "/homeMetaImg.jpg",
  },
  twitter: {
    card: "summary_large_image",
    title: "My Website",
    description: "A description for my website.",
    images: "/homeMetaImg.jpg",
  },
};

export default async function RootLayout({ children }) {
  // await connectMongo();
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="text-white bg-black">
        <AuthProvider>
          <CompareMovieProvider>{children}</CompareMovieProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
